In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r'F:\bank.csv')

In [3]:
dataset

age            job   marital  education default  balance housing loan  \
0       59         admin.   married  secondary      no     2343     yes   no   
1       56         admin.   married  secondary      no       45      no   no   
2       41     technician   married  secondary      no     1270     yes   no   
3       55       services   married  secondary      no     2476     yes   no   
4       54         admin.   married   tertiary      no      184      no   no   
5       42     management    single   tertiary      no        0     yes  yes   
6       56     management   married   tertiary      no      830     yes  yes   
7       60        retired  divorced  secondary      no      545     yes   no   
8       37     technician   married  secondary      no        1     yes   no   
9       28       services    single  secondary      no     5090     yes   no   
10      38         admin.    single  secondary      no      100     yes   no   
11      30    blue-collar   married  secondary      no      309     yes   no   
12      29     management   married   tertiary      no      199     yes  yes   
13      46    blue-collar    single   tertiary      no      460     yes   no   
14      31     technician    single   tertiary      no      703     yes   no   
15      35     management  divorced   tertiary      no     3837     yes   no   
16      32    blue-collar    single    primary      no      611     yes   no   
17      49       services   married  secondary      no       -8     yes   no   
18      41         admin.   married  secondary      no       55     yes   no   
19      49         admin.  divorced  secondary      no      168     yes  yes   
20      28         admin.  divorced  secondary      no      785     yes   no   
21      43     management    single   tertiary      no     2067     yes   no   
22      43     management  divorced   tertiary      no      388     yes   no   
23      43    blue-collar   married    primary      no     -192     yes   no   
24      37     unemployed    single  secondary      no      381     yes   no   
25      35    blue-collar    single  secondary      no       40     yes   no   
26      31     technician    single   tertiary      no       22     yes   no   
27      43    blue-collar    single  secondary      no        3     yes   no   
28      31         admin.   married  secondary      no      307     yes   no   
29      28    blue-collar    single  secondary      no      759     yes   no   
...    ...            ...       ...        ...     ...      ...     ...  ...   
11132   32    blue-collar   married  secondary      no     -325     yes  yes   
11133   37     management   married   tertiary      no     1594     yes   no   
11134   58  self-employed   married   tertiary      no     2596      no   no   
11135   36       services  divorced  secondary      no      115      no   no   
11136   31     management    single   tertiary      no        0     yes   no   
11137   49        retired   married    unknown      no      247      no   no   
11138   32     technician   married  secondary      no      235     yes   no   
11139   30  self-employed    single   tertiary      no     2593      no   no   
11140   55       services  divorced  secondary      no     2166     yes   no   
11141   32    blue-collar   married  secondary      no      130     yes   no   
11142   52         admin.  divorced  secondary      no       48      no  yes   
11143   38     unemployed  divorced  secondary      no      189     yes  yes   
11144   60        retired   married  secondary      no        0     yes   no   
11145   60        retired  divorced   tertiary      no     -134      no   no   
11146   30         admin.   married  secondary     yes       23      no  yes   
11147   44     unemployed   married  secondary      no        0      no   no   
11148   32    blue-collar   married  secondary      no        1     yes   no   
11149   46   entrepreneur   married  secondary      no     3317      no   no   
11150  

In [4]:
dataset.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [5]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [6]:
x=dataset.iloc[:,:16].values
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [7]:
y=dataset.iloc[:,16].values
y

array(['yes', 'yes', 'yes', ..., 'no', 'no', 'no'], dtype=object)

In [8]:
x.shape

(11162, 16)

In [9]:
y.shape

(11162,)

In [10]:
from sklearn.preprocessing import LabelEncoder 

In [11]:
le=LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])
x

array([[59, 0, 'married', ..., -1, 0, 'unknown'],
       [56, 0, 'married', ..., -1, 0, 'unknown'],
       [41, 9, 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 9, 'single', ..., -1, 0, 'unknown'],
       [43, 9, 'married', ..., 172, 5, 'failure'],
       [34, 9, 'married', ..., -1, 0, 'unknown']], dtype=object)

In [12]:
le1=LabelEncoder()
x[:,2]=le1.fit_transform(x[:,2])
x

array([[59, 0, 1, ..., -1, 0, 'unknown'],
       [56, 0, 1, ..., -1, 0, 'unknown'],
       [41, 9, 1, ..., -1, 0, 'unknown'],
       ...,
       [32, 9, 2, ..., -1, 0, 'unknown'],
       [43, 9, 1, ..., 172, 5, 'failure'],
       [34, 9, 1, ..., -1, 0, 'unknown']], dtype=object)

In [13]:
le2=LabelEncoder()
x[:,3]=le2.fit_transform(x[:,3])
x

array([[59, 0, 1, ..., -1, 0, 'unknown'],
       [56, 0, 1, ..., -1, 0, 'unknown'],
       [41, 9, 1, ..., -1, 0, 'unknown'],
       ...,
       [32, 9, 2, ..., -1, 0, 'unknown'],
       [43, 9, 1, ..., 172, 5, 'failure'],
       [34, 9, 1, ..., -1, 0, 'unknown']], dtype=object)

In [14]:
le3=LabelEncoder()
x[:,4]=le3.fit_transform(x[:,4])
x

array([[59, 0, 1, ..., -1, 0, 'unknown'],
       [56, 0, 1, ..., -1, 0, 'unknown'],
       [41, 9, 1, ..., -1, 0, 'unknown'],
       ...,
       [32, 9, 2, ..., -1, 0, 'unknown'],
       [43, 9, 1, ..., 172, 5, 'failure'],
       [34, 9, 1, ..., -1, 0, 'unknown']], dtype=object)

In [15]:
le4=LabelEncoder()
x[:,6]=le4.fit_transform(x[:,6])
x

array([[59, 0, 1, ..., -1, 0, 'unknown'],
       [56, 0, 1, ..., -1, 0, 'unknown'],
       [41, 9, 1, ..., -1, 0, 'unknown'],
       ...,
       [32, 9, 2, ..., -1, 0, 'unknown'],
       [43, 9, 1, ..., 172, 5, 'failure'],
       [34, 9, 1, ..., -1, 0, 'unknown']], dtype=object)

In [16]:
le5=LabelEncoder()
x[:,7]=le5.fit_transform(x[:,7])
x

array([[59, 0, 1, ..., -1, 0, 'unknown'],
       [56, 0, 1, ..., -1, 0, 'unknown'],
       [41, 9, 1, ..., -1, 0, 'unknown'],
       ...,
       [32, 9, 2, ..., -1, 0, 'unknown'],
       [43, 9, 1, ..., 172, 5, 'failure'],
       [34, 9, 1, ..., -1, 0, 'unknown']], dtype=object)

In [17]:
le6=LabelEncoder()
x[:,8]=le6.fit_transform(x[:,8])
x

array([[59, 0, 1, ..., -1, 0, 'unknown'],
       [56, 0, 1, ..., -1, 0, 'unknown'],
       [41, 9, 1, ..., -1, 0, 'unknown'],
       ...,
       [32, 9, 2, ..., -1, 0, 'unknown'],
       [43, 9, 1, ..., 172, 5, 'failure'],
       [34, 9, 1, ..., -1, 0, 'unknown']], dtype=object)

In [18]:
le7=LabelEncoder()
x[:,10]=le7.fit_transform(x[:,10])
x

array([[59, 0, 1, ..., -1, 0, 'unknown'],
       [56, 0, 1, ..., -1, 0, 'unknown'],
       [41, 9, 1, ..., -1, 0, 'unknown'],
       ...,
       [32, 9, 2, ..., -1, 0, 'unknown'],
       [43, 9, 1, ..., 172, 5, 'failure'],
       [34, 9, 1, ..., -1, 0, 'unknown']], dtype=object)

In [19]:
le8=LabelEncoder()
x[:,15]=le8.fit_transform(x[:,15])
x

array([[59, 0, 1, ..., -1, 0, 3],
       [56, 0, 1, ..., -1, 0, 3],
       [41, 9, 1, ..., -1, 0, 3],
       ...,
       [32, 9, 2, ..., -1, 0, 3],
       [43, 9, 1, ..., 172, 5, 0],
       [34, 9, 1, ..., -1, 0, 3]], dtype=object)

In [20]:
le9=LabelEncoder()
y[:,]=le8.fit_transform(y[:,])
y

array([1, 1, 1, ..., 0, 0, 0], dtype=object)

In [21]:
x.shape

(11162, 16)

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [23]:
oh=OneHotEncoder(categorical_features=[1])
x=oh.fit_transform(x).toarray()
x

C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[  1.,   0.,   0., ...,  -1.,   0.,   3.],
       [  1.,   0.,   0., ...,  -1.,   0.,   3.],
       [  0.,   0.,   0., ...,  -1.,   0.,   3.],
       ...,
       [  0.,   0.,   0., ...,  -1.,   0.,   3.],
       [  0.,   0.,   0., ..., 172.,   5.,   0.],
       [  0.,   0.,   0., ...,  -1.,   0.,   3.]])

In [24]:
x.shape


(11162, 27)

In [25]:
x=x[:,1:] #removing dummy
x.shape

(11162, 26)

In [26]:
oh1=OneHotEncoder(categorical_features=[12])
x=oh1.fit_transform(x).toarray()
x

C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[  0.,   1.,   0., ...,  -1.,   0.,   3.],
       [  0.,   1.,   0., ...,  -1.,   0.,   3.],
       [  0.,   1.,   0., ...,  -1.,   0.,   3.],
       ...,
       [  0.,   0.,   1., ...,  -1.,   0.,   3.],
       [  0.,   1.,   0., ..., 172.,   5.,   0.],
       [  0.,   1.,   0., ...,  -1.,   0.,   3.]])

In [27]:
x.shape

(11162, 28)

In [28]:
x=x[:,1:] #removing dummy
x.shape

(11162, 27)

In [29]:
oh2=OneHotEncoder(categorical_features=[14])
x=oh2.fit_transform(x).toarray()
x

C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[  0.,   1.,   0., ...,  -1.,   0.,   3.],
       [  0.,   1.,   0., ...,  -1.,   0.,   3.],
       [  0.,   1.,   0., ...,  -1.,   0.,   3.],
       ...,
       [  0.,   1.,   0., ...,  -1.,   0.,   3.],
       [  0.,   1.,   0., ..., 172.,   5.,   0.],
       [  0.,   1.,   0., ...,  -1.,   0.,   3.]])

In [30]:
x.shape

(11162, 30)

In [31]:
x=x[:,1:] #removing dummy
x.shape

(11162, 29)

In [32]:
oh3=OneHotEncoder(categorical_features=[21])
x=oh3.fit_transform(x).toarray()
x

C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[  0.,   0.,   1., ...,  -1.,   0.,   3.],
       [  0.,   0.,   1., ...,  -1.,   0.,   3.],
       [  0.,   0.,   1., ...,  -1.,   0.,   3.],
       ...,
       [  1.,   0.,   0., ...,  -1.,   0.,   3.],
       [  1.,   0.,   0., ..., 172.,   5.,   0.],
       [  1.,   0.,   0., ...,  -1.,   0.,   3.]])

In [33]:
x.shape

(11162, 31)

In [34]:
x=x[:,1:] #removing dummy
x.shape

(11162, 30)

In [35]:
oh4=OneHotEncoder(categorical_features=[24])
x=oh4.fit_transform(x).toarray()
x

C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[  0.,   0.,   0., ...,  -1.,   0.,   3.],
       [  0.,   0.,   0., ...,  -1.,   0.,   3.],
       [  0.,   0.,   0., ...,  -1.,   0.,   3.],
       ...,
       [  0.,   1.,   0., ...,  -1.,   0.,   3.],
       [  0.,   0.,   0., ..., 172.,   5.,   0.],
       [  0.,   0.,   0., ...,  -1.,   0.,   3.]])

In [36]:
x.shape

(11162, 41)

In [37]:
x=x[:,1:] #removing dummy
x.shape

(11162, 40)

In [38]:
oh5=OneHotEncoder(categorical_features=[39])
x=oh5.fit_transform(x).toarray()
x

C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Shravya Banala\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[  0.,   0.,   0., ...,   1.,  -1.,   0.],
       [  0.,   0.,   0., ...,   1.,  -1.,   0.],
       [  0.,   0.,   0., ...,   1.,  -1.,   0.],
       ...,
       [  0.,   0.,   0., ...,   2.,  -1.,   0.],
       [  1.,   0.,   0., ...,   2., 172.,   5.],
       [  0.,   0.,   0., ...,   1.,  -1.,   0.]])

In [39]:
x.shape

(11162, 43)

In [40]:
x=x[:,1:] #removing dummy
x.shape

(11162, 42)

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [42]:
#standard scaling...
# to increase accuracy
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)


In [43]:
import keras
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()
model.add(Dense(input_dim=42,init="random_uniform",output_dim=68,activation="relu")) 
model.add(Dense(init="random_uniform",output_dim=92,activation="relu")) 
model.add(Dense(init="random_uniform",output_dim=1,activation="sigmoid")) 
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=100,batch_size=32)


Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.


C:\Users\Shravya Banala\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=42, activation="relu", units=68, kernel_initializer="random_uniform")`
  """
C:\Users\Shravya Banala\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=92, kernel_initializer="random_uniform")`
  
C:\Users\Shravya Banala\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  import sys


Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8929/8929 [==============================] - 3s 350us/step - loss: 0.4433 - acc: 0.8068
Epoch 2/100
8929/8929 [==============================] - 1s 81us/step - loss: 0.3628 - acc: 0.8471
Epoch 3/100
8929/8929 [==============================] - 1s 82us/step - loss: 0.3486 - acc: 0.8542
Epoch 4/100
8929/8929 [==============================] - 1s 85us/step - loss: 0.3359 - acc: 0.8582
Epoch 5/100
8929/8929 [==============================] - 1s 83us/step - loss: 0.3266 - acc: 0.8647
Epoch 6/100
8929/8929 [==============================] - 1s 81us/step - loss: 0.3176 - acc: 0.8695
Epoch 7/100
8929/8929 [==============================] - 1s 79us/step - loss: 0.3130 - acc: 0.8737
Epoch 8/100
8929/8929 [==============================] - 1s 79us/step - loss: 0.3141 - acc: 0.8666
Epoch 9/100
8929/8929 [==============================] - 1s 79us/step - loss: 0.3010 - acc: 0.8786
Epoch 10/100
8929/8929 [==============================] - 1s

8929/8929 [==============================] - 1s 87us/step - loss: 0.0963 - acc: 0.9657
Epoch 81/100
8929/8929 [==============================] - 1s 84us/step - loss: 0.0991 - acc: 0.9605
Epoch 82/100
8929/8929 [==============================] - 1s 95us/step - loss: 0.0892 - acc: 0.9654
Epoch 83/100
8929/8929 [==============================] - 1s 97us/step - loss: 0.0875 - acc: 0.9667
Epoch 84/100
8929/8929 [==============================] - 1s 96us/step - loss: 0.0902 - acc: 0.9644
Epoch 85/100
8929/8929 [==============================] - 1s 101us/step - loss: 0.0915 - acc: 0.9655
Epoch 86/100
8929/8929 [==============================] - 1s 97us/step - loss: 0.0883 - acc: 0.9664
Epoch 87/100
8929/8929 [==============================] - 1s 85us/step - loss: 0.0864 - acc: 0.9663
Epoch 88/100
8929/8929 [==============================] - 1s 86us/step - loss: 0.0850 - acc: 0.9695
Epoch 89/100
8929/8929 [==============================] - 1s 85us/step - loss: 0.0819 - acc: 0.9711
Epoch 90/100

In [44]:
y_pred=model.predict(x_test)
y_pred

array([[1.1926919e-01],
       [9.9996424e-01],
       [0.0000000e+00],
       ...,
       [9.0153891e-01],
       [5.9604645e-08],
       [1.9375255e-03]], dtype=float32)

In [45]:
y_pred=(y_pred>0.5)  #above 0.5 takes true
y_pred

array([[False],
       [ True],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [46]:
#from sklearn.metrics import accuracy_score


In [47]:
#test=accuracy_score(y_pred,y_test)
#test

In [48]:
score=model.evaluate(x_train,y_train)

8929/8929 [==============================] - 1s 68us/step


In [49]:
print("accuracy : "+str(score[1]*100))

accuracy : 98.18568708701983


In [50]:
x_test[0]

array([-0.22657536, -0.32939951, -1.7046845 , -0.39913565, -0.09686471,
       -0.27410848, -0.17488949, -0.39459853, -0.34910544, -0.15930776,
        1.70870313, -0.30215554, -0.1931085 , -0.16761389, -0.27292594,
       -0.51695631, -0.98411098, -0.69993206,  4.5996008 ,  0.86351031,
       -0.66975544, -0.45760242, -0.17658264, -0.1589378 , -0.54192526,
       -0.27363591, -0.1931085 ,  3.28561172, -0.17992689, -0.44212513,
       -0.18025832, -0.08293772, -0.02094658, -0.12621015, -0.45070573,
        1.05825117, -0.39003722, -0.54805313, -0.76762927, -0.56394809,
        2.61598774,  0.48684529])